FROM python:3.9.6
LABEL maintainer='p-geon'

RUN pip install -q --upgrade pip && \
    pip install -q \
        tokenizers==0.12.1 \
        transformers[tf-cpu]==4.18.0 \
        fugashi==1.1.2 \
        ipadic==1.0.0 \
        jupyter==1.0.0
# transformers[torch]==4.18.0 is also available instead of transformers[tf-cpu]


WORKDIR /work
USER root
CMD ["/bin/bash"]