FROM python:3.9.6
LABEL maintainer='p-geon'

ARG requirements_txt
COPY $requirements_txt ./$requirements_txt
RUN pip install -q --upgrade pip && \
    pip install -r $requirements_txt  -q

WORKDIR /work
USER root
CMD ["/bin/bash"]