FROM python:3.9.6
LABEL maintainer='p-geon'

RUN pip install -q --upgrade pip
RUN pip install -q tokenizers==0.12.1
RUN pip install -q transformers[tf-cpu]==4.18.0
RUN pip install -q fugashi==1.1.2
RUN pip install -q ipadic==1.0.0
# torch: RUN pip install -q transformers[torch]==4.18.0

WORKDIR /work
USER root
CMD ["/bin/bash"]