FROM python:3.9.6 as base-image
LABEL maintainer='p-geon'

RUN apt-get update -q && apt-get install -y -q --no-install-recommends \
  mecab \
  libmecab-dev \
  mecab-ipadic \
  mecab-ipadic-utf8

RUN git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git && \
  cd mecab-ipadic-neologd && \
  ./bin/install-mecab-ipadic-neologd -n -a --forceyes --asuser


FROM python:3.9.6
ARG path_neologd
COPY --from=base-image $path_neologd $path_neologd

RUN pip install -q --upgrade pip && \
    pip install -q mecab-python3==1.0.5

WORKDIR /work
USER root
CMD ["/bin/bash"]